# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
executors:
  rqueue-executor:
    machine:
      image: ubuntu-1604:202007-01

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      ORG_GRADLE_PROJECT_sonatypeUsername: xxx
      ORG_GRADLE_PROJECT_sonatypePassword: xxx
      USER_NAME: rqueue
      REDIS_RUNNING: "true"
      CI_ENV: "true"

jobs:
  boot_2_1:
    executor: rqueue-executor
    environment:
      SPRING_BOOT_VERSION: 2.1.0.RELEASE
      SPRING_VERSION: 5.1.2.RELEASE
      SPRING_DATA_VERSION: 2.1.2.RELEASE
      MICROMETER_VERSION: 1.1.0

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: sudo apt-get update
      - run: sudo apt-get install redis-server
      - run: mkdir 9000 9001 9002 9003 9004 9005
      - run: printf "port 9000 \ncluster-enabled yes \ncluster-config-file nodes.conf \ncluster-node-timeout 5000 \nappendonly yes" >> 9000/redis.conf
      - run: printf "port 9001 \ncluster-enabled yes \ncluster-config-file nodes.conf \ncluster-node-timeout 5000 \nappendonly yes" >> 9001/redis.conf
      - run: printf "port 9002 \ncluster-enabled yes \ncluster-config-file nodes.conf \ncluster-node-timeout 5000 \nappendonly yes" >> 9002/redis.conf
      - run: printf "port 9003 \ncluster-enabled yes \ncluster-config-file nodes.conf \ncluster-node-timeout 5000 \nappendonly yes" >> 9003/redis.conf
      - run: printf "port 9004 \ncluster-enabled yes \ncluster-config-file nodes.conf \ncluster-node-timeout 5000 \nappendonly yes" >> 9004/redis.conf
      - run: printf "port 9005 \ncluster-enabled yes \ncluster-config-file nodes.conf \ncluster-node-timeout 5000 \nappendonly yes" >> 9005/redis.conf
      - run: cd 9000 && redis-server ./redis.conf &
      - run: cd 9001 && redis-server ./redis.conf &
      - run: cd 9002 && redis-server ./redis.conf &
      - run: cd 9003 && redis-server ./redis.conf &
      - run: cd 9004 && redis-server ./redis.conf &
      - run: cd 9005 && redis-server ./redis.conf &
      - run: redis-cli --cluster create 127.0.0.1:9000 127.0.0.1:9001 127.0.0.1:9002 127.0.0.1:9003 127.0.0.1:9004 127.0.0.1:9005 --cluster-replicas 1 --cluster-yes
      - run: df -h
      - run: lscpu
      - run: ./gradlew codeCoverageReport
      - run:
          name: Build Success
          when: on_success
          command: ./gradlew coveralls

  boot_2_2:
    executor: rqueue-executor
    environment:
      SPRING_BOOT_VERSION: 2.2.0.RELEASE
      SPRING_VERSION: 5.2.0.RELEASE
      SPRING_DATA_VERSION: 2.2.0.RELEASE
      MICROMETER_VERSION: 1.3.2
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v2-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: ./gradlew codeCoverageReport
      - run:
          name: Build Success
          when: on_success
          command: ./gradlew coveralls


workflows:
  main:
    jobs:
      - boot_2_1
      - boot_2_2
